feat: Integrate language support for multiple languages in the application
OpenSignLabs/OpenSign pull request #1019
Opened 2024-08-07 12:14 UTC by raktima-opensignlabs

2024-08-07 16:58 UTC, Zathiel requested changes
hey @raktima-opensignlabs few changes on all the specific item mentionned

Make sure every field is Caps Lock on first later

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +    "login": "se connecter",
"login": "Se Connecter",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +    "job-title":"Titre d'emploi",
"job-title":"Organisation",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +      "Name":"Nom",
"name":"Nom et Prénom",

User can missunderstand and only write his Name and not firstname

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +    "disable-documentId":"Désactiver l'ID de document",
"disable-documentId":"Désactiver l'ID du document",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +    "change-password":"Changer le mot de passe",
"change-password":"Changer votre mot de passe",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +    "plan":"Plan",
"plan":"Offre",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +    "tour-content":"Ne montre plus ça",
"tour-content":"Ne plus afficher",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +    "tagline-help":"Ce slogan apparaîtra sur votre profil public OpenSign par exemple. https://opensign.me/alex",
"tagline-help":"Ce surnom apparaîtra sur votre profil public OpenSign par exemple. https://opensign.me/alex",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +    "password-length":"Le mot de passe doit être 8 Longs caractères",
"password-length":"Le mot de passe doit être de plus de 8 caractères",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +    "password-case":"Le mot de passe doit contenir lettre majuscule, lettre minuscule, chiffre",
"password-case":"Le mot de passe doit contenir une lettre majuscule, minuscule et un chiffre ",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +      "Need your sign": "Besoin de signer",
"Need your sign": "Besoin de votre signature",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +      "Declined": "a refusé",
"Declined": "Signature refusé",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +    "Out for signatures":"En quête de signatures"
"Out for signatures":"En attente de Signature"

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +      "Draft Documents":"Projets de documents",
"Draft Documents":"Brouillons",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +      "Need your sign":"Besoin de votre signe",
"Need your sign":"Besoin de votre signature",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +      "Teams":"Teams",
"Teams":"Équipe",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +      "Sr.No":"Sr. Non",
"Sr.No":"Numéro du document",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +      "Name":"Nom",
"name":"Nom et Prénom",

User can missunderstand and only write his Name and not firstname

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +      "Type":"Taper"
"Type":"Saisir"

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +      "sign":"signe",
"sign":"Signer",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +      "Resend":"Renvoyer",
"Resend":"Relancer",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +        "Need your sign": "Voici une liste de documents qui attendent votre signature",
"Need your sign": "Voici une liste de documents ou votre signature est requise",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +      "send-in-order":"Envoyer dans la commande",
"send-in-order":"Envoyer dans l'ordre ?",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +     "OpenSign-drive":"Lecteur OpenSign™",
"OpenSign-drive":"Liste des Documents",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +      "Declined":"Diminué",
"Declined":"Refuser",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +     "no-data" :"Aucune donnée disponible",
"no-data" :"Aucune données disponible",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +      "parent-folder" :"Dossier parent",
"parent-folder" :"Dossier Parent",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +     "generate-token-alert":"Êtes-vous sûr de vouloir régénérer le jeton, il expirera à l'ancienne jeton?",
"generate-token-alert":"Êtes-vous sûr de vouloir régénérer le jeton, votre ancien jeton sera supprimer?",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +     "users-from-teams" :"utilisateurs de Teams",
"users-from-teams" :"utilisateurs de votre Équipe",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +        "stamp":"estampiller",
"stamp":"Tampon",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +        "name":"nom",
"name":"Nom et Prénom",

User can missunderstand and only write his Name and not firstname

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +        "job title":"titre d'emploi",
"job title":"Votre Fonction",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +        "company":"entreprise",
"company":"Organisation",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +     "document-signed-alert" :"Félicitations ! 🎉 Ce document a été signé avec succès par vous !",
"document-signed-alert" :"Félicitations ! 🎉 Votre document à bien été signer !",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +     "otp-sent-alert" :"OTP envoyé sur votre email",
"otp-sent-alert" :"Le code OTP a bien été envoyer sur votre adresse Email",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +     "choose-from-contacts":"Choisissez parmi les contacts",
"choose-from-contacts":"Choisissez parmis les contacts",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +     "Mails Sent" :"Mails envoyés",
"Mails Sent" :"Mails envoyés avec succès !",

2024-08-07 16:58 UTC, Zathiel commented on apps/OpenSign/public/locales/fr/translation.json
> +     "document-decline" :"Document-refus",
"document-decline" :"Document-refusé",

2024-08-07 17:02 UTC, Zathiel commented on apps/OpenSign/src/script/PublicTemplate.js
> +const serverUrl = "http://localhost:8080/app";
isn't a variable already push for that ?

2024-08-08 09:04 UTC, prafull-opensignlabs approved these changes

2024-08-08 09:05 UTC, prafull-opensignlabs approved these changes

2024-08-08 09:06 UTC, merged